language: cpp

services:
  - docker

before_install:
  - docker build -t test .
  - docker ps -a

script:
  - docker run -it test "./testit.sh"
env:
    - MAKE_ISOLATED="true"
    - MAKE_ISOLATED="false"
