language: cpp

services:
  - docker

before_install:
  - docker build -t test .
  - docker ps -a

script:
    - docker run -e MAKE_ISOLATED="$MAKE_ISOLATED" -it test "./testit.sh"
env:
    - MAKE_ISOLATED="true"
    - MAKE_ISOLATED="false"
